#!/usr/bin/env bash
# install nginx server

# update package info 
sudo apt-get update

# install Nginx
sudo apt-get -y install nginx

# allow incming HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP'

# sample text msg to defaulf Nginx page
echo "Hello world!" > /var/www/html/index.nginx-debian.html > /dev/null

# start nginx service
service nginx start
