#!/usr/bin/env bash
# install nginx server

# update package info 
sudo apt-get update

# install Nginx
sudo apt-get install nginx

# allow incming HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP'

# sample text msg to defaulf Nginx page
echo "Hello world!" | sudo tee /var/www/html/index.html

# start nginx service
sudo service nginx start
