#!/usr/bin/env bash

# update information and install nginx and star server
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello world!" > index.html
sudo mv index.html /var/www/html

# create custom 404 error and move page to web dir content

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    
    location / rediect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > default

# custom server configuration
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx retart
