#!/usr/bin/env bash
#  Bash script that stops 4-to_infinity_and_beyond process

#Get the id of the process
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminatethe initiative
if [ -n "$id" ]; then
   kill -15 "$id"
fi 
