#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd

# Only display username, id, home directory path of user

while read -r passwd; do 
  echo "$passwd" | cut  -d ':' -f1,3,6
done < "/etc/passwd"
