#!/usr/bin/env bash
# Script that displays "Best School" 10 times
# Display "Hi" on the 9th iter, before "Best School"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then 
    echo "Hi"
  fi 
    echo "Best School"
    (( count++ ))
done
