#!/usr/bin/env bash
# Bash script that change hostname address
cp /etc/hosts ~hosts.new
sed -i "s/^127[0-9]*\localhost/127.0.0.2 localhost/" ~/hosts.new
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
cp -f ~hosts.new /etc/hosts
